name: Build and publish release
on:
  push:
    tags:
      - 'v*'
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - run: ./gradlew build
      - id: read_changelog
        uses: mindsers/changelog-reader-action@v2
      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.read_changelog.outputs.changes }}
          files: 'build/libs/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
